config/routes.rb
Assignmentapp::Application.routes.draw do
  resources :storeorders

  resources :posts
  
  resources :products do
		resources :posts
  end

  resources :line_items

  resources :carts

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :orders

  resources :prescriptions

  resources :products

  resources :customers
  
  resources :sessions
  
  resources :products do
	resources :posts
  end
  
  match '/signin' => "sessions#new"
  match '/signout' => "sessions#destroy"
  match '/search' => 'products#search'

  

  root :to => 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
	current_item
	end
	
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end


end

app/models/customer.rb
class Customer < ActiveRecord::Base
has_many :prescriptions
has_many :orders
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
validates :name ,presence:true
validates :email ,uniqueness:true
has_many :posts, :dependent => :destroy

has_secure_password

geocoded_by :address
after_validation :geocode, :if => :address_changed?

	def age
		age = ((Date.current - self.dob)/ 365).to_i
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :storeorder
	
	def total_price
		product.price * quantity
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
belongs_to :product
belongs_to :customer
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :customer
belongs_to :product

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
belongs_to :product
belongs_to :customer
validates :prescriber ,presence:true
end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :prescriptions
has_many :orders
validates :name ,presence:true
validates :price ,presence:true
has_many :posts, :dependent => :destroy


has_many :line_items

def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['name LIKE  ?', search_condition])
end

before_destroy :ensure_not_referenced_by_any_line_item
#...

private
# ensure that there are no line items referencing this product
def ensure_not_referenced_by_any_line_item
	if line_items.empty?
		return true
	else
		errors.add(:base, 'Line Items present')
		return false
	end
end

end

app/models/storeorder.rb
class Storeorder < ActiveRecord::Base
validates :name, :address, :email, presence: true
has_many :line_items, dependent: :destroy

def add_line_items_from_cart(cart)
	cart.line_items.each do |item|
	item.cart_id = nil
	line_items << item
	end
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    #@cart = Cart.find(params[:id])
	@cart = current_cart
    @cart.destroy
	session[:cart_id] = nil

    respond_to do |format|
      #format.html { redirect_to carts_url }
	  format.html { redirect_to carts_url,notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authorise
def create
	@product = Product.find params[:product_id]
	@post = @product.posts.create params[:post]
	@post.customer_id = @current_customer.id   #sets the customer_id FK
	@post.save		#saves the @post
				#object to the posts table
		respond_to do |format|
			format.js
			format.html{ redirect_to @product }
		end
	
end

def destroy
		@product = Product.find params[:product_id]
		@post = Post.find (params[:id])	
		@post.destroy
	
	respond_to do |format|
		format.html {redirect_to @product}
		end
end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @prescriptions = Prescription.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prescriptions }
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prescription }
    end
  end

  # GET /prescriptions/new
  # GET /prescriptions/new.json
  def new
    @prescription = Prescription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prescription }
    end
  end

  # GET /prescriptions/1/edit
  def edit
    @prescription = Prescription.find(params[:id])
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(params[:prescription])

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render json: @prescription, status: :created, location: @prescription }
      else
        format.html { render action: "new" }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prescriptions/1
  # PUT /prescriptions/1.json
  def update
    @prescription = Prescription.find(params[:id])

    respond_to do |format|
      if @prescription.update_attributes(params[:prescription])
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to prescriptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def signed_in?
       if session[:customer_id].nil?
			return
       else
			@current_customer = Customer.find_by_id(session[:customer_id])
       end
  end
  
  #def euro(amount)               #method with a formal parameter, no need
#number_to_currency(amount, :unit => "&euro;")
  #end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/storeorders_helper.rb
module StoreordersHelper
end

app/views/prescriptions/_form.html.erb
<%= form_for(@prescription) do |f| %>
  <% if @prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @prescription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.collection_select :product_id, Product.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :dosage %><br />
    <%= f.text_field :dosage %>
  </div>
  <div class="field">
    <%= f.label :limit %><br />
    <%= f.number_field :limit %>
  </div>
  <div class="field">
    <%= f.label :expirydate %><br />
    <%= f.date_select :expirydate %>
  </div>
  <div class="field">
    <%= f.label :prescriber %><br />
    <%= f.text_field :prescriber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing prescription</h1>

<%= render 'form' %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<h1>Listing prescriptions</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Product</th>
    <th>Dosage</th>
    <th>Limit</th>
    <th>Expiry date</th>
    <th>Prescriber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prescriptions.each do |prescription| %>
  <tr>
    <td><%= prescription.customer.name %></td>
    <td><%= prescription.product.name %></td>
    <td><%= prescription.dosage %></td>
    <td><%= prescription.limit %></td>
    <td><%= prescription.expirydate %></td>
    <td><%= prescription.prescriber %></td>
    <td><%= link_to 'Show', prescription %></td>
    <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
    <td><%= link_to 'Destroy', prescription, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New prescription</h1>

<%= render 'form' %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @prescription.customer.name %>
</p>

<p>
  <b>Product:</b>
  <%= @prescription.product.name %>
</p>

<p>
  <b>Dosage:</b>
  <%= @prescription.dosage %>
</p>

<p>
  <b>Limit:</b>
  <%= @prescription.limit %>
</p>

<p>
  <b>Expirydate:</b>
  <%= @prescription.expirydate %>
</p>

<p>
  <b>Prescriber:</b>
  <%= @prescription.prescriber %>
</p>


<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>