config/routes.rb
Assignmentapp::Application.routes.draw do
  resources :storeorders

  resources :posts
  
  resources :products do
		resources :posts
  end

  resources :line_items

  resources :carts

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :orders

  resources :prescriptions

  resources :products

  resources :customers
  
  resources :sessions
  
  resources :products do
	resources :posts
  end
  
  match '/signin' => "sessions#new"
  match '/signout' => "sessions#destroy"
  match '/search' => 'products#search'

  

  root :to => 'pages#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	
	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
	current_item
	end
	
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end


end

app/models/customer.rb
class Customer < ActiveRecord::Base
has_many :prescriptions
has_many :orders
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
validates :name ,presence:true
validates :email ,uniqueness:true
has_many :posts, :dependent => :destroy

has_secure_password

geocoded_by :address
after_validation :geocode, :if => :address_changed?

	def age
		age = ((Date.current - self.dob)/ 365).to_i
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :storeorder
	
	def total_price
		product.price * quantity
	end

end

app/models/order.rb
class Order < ActiveRecord::Base
belongs_to :product
belongs_to :customer
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :customer
belongs_to :product

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
belongs_to :product
belongs_to :customer
validates :prescriber ,presence:true
end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :prescriptions
has_many :orders
validates :name ,presence:true
validates :price ,presence:true
has_many :posts, :dependent => :destroy


has_many :line_items

def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['name LIKE  ?', search_condition])
end

before_destroy :ensure_not_referenced_by_any_line_item
#...

private
# ensure that there are no line items referencing this product
def ensure_not_referenced_by_any_line_item
	if line_items.empty?
		return true
	else
		errors.add(:base, 'Line Items present')
		return false
	end
end

end

app/models/storeorder.rb
class Storeorder < ActiveRecord::Base
validates :name, :address, :email, presence: true
has_many :line_items, dependent: :destroy

def add_line_items_from_cart(cart)
	cart.line_items.each do |item|
	item.cart_id = nil
	line_items << item
	end
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    #@cart = Cart.find(params[:id])
	@cart = current_cart
    @cart.destroy
	session[:cart_id] = nil

    respond_to do |format|
      #format.html { redirect_to carts_url }
	  format.html { redirect_to carts_url,notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authorise, :only => [:new, :edit, :delete]
   #before_filter :authorise, :except => [:index, :show]
   
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authorise
def create
	@product = Product.find params[:product_id]
	@post = @product.posts.create params[:post]
	@post.customer_id = @current_customer.id   #sets the customer_id FK
	@post.save		#saves the @post
				#object to the posts table
		respond_to do |format|
			format.js
			format.html{ redirect_to @product }
		end
	
end

def destroy
		@product = Product.find params[:product_id]
		@post = Post.find (params[:id])	
		@post.destroy
	
	respond_to do |format|
		format.html {redirect_to @product}
		end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def signed_in?
       if session[:customer_id].nil?
			return
       else
			@current_customer = Customer.find_by_id(session[:customer_id])
       end
  end
  
  #def euro(amount)               #method with a formal parameter, no need
#number_to_currency(amount, :unit => "&euro;")
  #end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/storeorders_helper.rb
module StoreordersHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
	<th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<h2>Your Pragmatic Cart</h2>
<div class="cart_title">Your Cart</div>
	<table>
	<% @cart.line_items.each do |item| %>
	<tr>
		<td><%= item.quantity %>&times;</td>
		<td><%= item.product.name %></td>
		<td class="item_price"><%= number_to_currency(item.total_price) %></td>
	</tr>
<% end %>

<tr class="total_line">
<td colspan="2">Total</td>
<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
</tr>
</table>

<%= button_to "Checkout", new_storeorder_path, method: :get %>
<%= button_to 'Empty cart', @cart, method: :delete, confirm: 'Are you sure?' %>

<%= link_to 'Back', carts_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.collection_select :product_id, Product.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :deliverycharge %><br />
    <%= f.text_field :deliverycharge %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Product</th>
    <th>Date</th>
    <th>Delivery Charge</th>
    <th>Total Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.customer.name %></td>
    <td><%= order.product.name %></td>
    <td><%= order.date %></td>
    <td><%= order.deliverycharge %></td>
    <td><%= order.total %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @order.customer.name %>
</p>

<p>
  <b>Product:</b>
  <%= @order.product.name %>
</p>

<p>
  <b>Date:</b>
  <%= @order.date %>
</p>

<p>
  <b>Delivery Charge:</b>
  <%= @order.deliverycharge %>
</p>

<p>
  <b>Total Cost:</b>
  <%= @order.total %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>