config/routes.rb
Assignmentapp::Application.routes.draw do
  resources :storeorders

  resources :posts
  
  resources :products do
		resources :posts
  end

  resources :line_items

  resources :carts

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"

  resources :orders

  resources :prescriptions

  resources :products

  resources :customers
  
  resources :sessions
  
  resources :products do
	resources :posts
  end
  
  match '/signin' => "sessions#new"
  match '/signout' => "sessions#destroy"
  match '/search' => 'products#search'

  

  root :to => 'pages#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :prescriptions
has_many :orders
validates :name ,presence:true
validates :price ,presence:true
has_many :posts, :dependent => :destroy


has_many :line_items

def self.search(search)
   search_condition = search + "%"
   find(:all, :conditions => ['name LIKE  ?', search_condition])
end

before_destroy :ensure_not_referenced_by_any_line_item
#...

private
# ensure that there are no line items referencing this product
def ensure_not_referenced_by_any_line_item
	if line_items.empty?
		return true
	else
		errors.add(:base, 'Line Items present')
		return false
	end
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  before_filter :authorise		#forces this method to execute so
								#that @current_customer will be populated
	
  
  def index
    #@products = Product.all
	@products = Product.paginate(:page => params[:page], :per_page => 3)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end
  
  #def search
	#@products = Product.search params[:q]
	#render 'index'                  #or whatever view is needed
  #end
  
  def search
	#@products = Product.search params[:q]
	@products = Product.paginate(:page => params[:page], :per_page => 3).search params[:q]
	unless @products.empty?
		render 'index'             #or whatever view is needed
	else
		flash[:notice] = 'No product matches that search'
		render 'index'
	end
	flash[:notice] = nil
  end


  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :prescriptionreq %><br />
    <%= f.check_box :prescriptionreq %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_search.html.erb
<%= form_tag("/search", :method => "get") do %>
   <%= label_tag(:q, "Search for:") %>
   <%= text_field_tag(:q, params[:q], :id => 'q_field') %>
   <%= submit_tag("Search") %>
<% end %> 

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<%= will_paginate @products%>
<div id="search">
	<%= render :partial => 'products/search' %>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Brand</th>
    <th>Price</th>
    <th>Size</th>
    <th>Prescription Required</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= image_tag(product.brand, :size => "50x50", :alt=> "Image not found") %></td>
    <td><%= product.price %></td>
    <td><%= product.size %></td>
    <td><%= product.prescriptionreq %></td>
	<td><%= button_to 'Add to Cart', line_items_path(product_id: product) %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Brand:</b>
  <%= image_tag(@product.brand, :size => "50x50", :alt=> "Image not found") %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Size:</b>
  <%= @product.size %>
</p>

<p>
  <b>Prescriptionreq:</b>
  <%= @product.prescriptionreq %>
</p>

<h2>Please leave a comment:</h2>
	<%= form_for([@product, Post.new]) do |f| %>
		<%= f.text_area :content, :rows => 3 %>
			<div class="actions">
				<%= f.submit "Post a Comment" %>
			</div>
	<% end %>

<% if @product.posts.empty? %>
	<h3>You are the first to comment </h3>
<% else %>	
<h2>What others felt about this:</h2>
	 <% @product.posts.reverse.each do |post| %>
		<p><%= post.content %>
		Posted <%= time_ago_in_words(post.created_at) %> ago by
				<%= post.customer.name %></p>
				<%= link_to "destroy", [@product, post], method: :delete, data: { confirm: 'Are you sure?'} %>
		<% end %>
<% end %>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>